const sampleTasks = [
    {
      id: 1,
      title: 'Finish React project',
      description: 'Complete all components and add state management.',
      dueDate: '2024-12-01',
      priority: 'High',
      completed: false,
    },
    {
      id: 2,
      title: 'Write blog post',
      description: 'Write a technical article about hooks in React.',
      dueDate: '2024-11-20',
      priority: 'Medium',
      completed: false,
    },
    {
      id: 3,
      title: 'Schedule team meeting',
      description: 'Discuss project milestones and assign tasks.',
      dueDate: '2024-11-15',
      priority: 'Low',
      completed: true,
    },
    {
      id: 4,
      title: 'Plan holiday trip',
      description: 'Research destinations and accommodations.',
      dueDate: '2024-12-05',
      priority: 'Low',
      completed: false,
    },
    {
      id: 5,
      title: 'Update resume',
      description: 'Add recent projects and update skills section.',
      dueDate: '2024-11-18',
      priority: 'High',
      completed: false,
    },
    {
      id: 6,
      title: 'Complete coding challenge',
      description: 'Solve a few problems on LeetCode.',
      dueDate: '2024-11-10',
      priority: 'High',
      completed: false,
    },
    {
      id: 7,
      title: 'Buy groceries',
      description: 'Pick up some essentials: milk, bread, eggs.',
      dueDate: '2024-11-14',
      priority: 'Medium',
      completed: false,
    },
    {
      id: 8,
      title: 'Prepare dinner',
      description: 'Make a healthy dinner: grilled chicken with vegetables.',
      dueDate: '2024-11-14',
      priority: 'Low',
      completed: false,
    },
    {
      id: 9,
      title: 'Attend webinar',
      description: 'Join the webinar about React performance optimization.',
      dueDate: '2024-11-12',
      priority: 'Medium',
      completed: true,
    },
    {
      id: 10,
      title: 'Write code review feedback',
      description: 'Review the code submitted by the team and provide feedback.',
      dueDate: '2024-11-13',
      priority: 'Medium',
      completed: false,
    },
    {
      id: 11,
      title: 'Read React documentation',
      description: 'Go through the latest React documentation for updates.',
      dueDate: '2024-11-09',
      priority: 'Low',
      completed: false,
    },
    {
      id: 12,
      title: 'Take online course',
      description: 'Complete module 3 of the JavaScript Mastery course.',
      dueDate: '2024-11-22',
      priority: 'High',
      completed: false,
    },
    {
      id: 13,
      title: 'Clean the house',
      description: 'Tidy up the living room and kitchen.',
      dueDate: '2024-11-14',
      priority: 'Medium',
      completed: false,
    },
    {
      id: 14,
      title: 'Organize desk',
      description: 'Sort through papers and organize office supplies.',
      dueDate: '2024-11-07',
      priority: 'Low',
      completed: true,
    },
    {
      id: 15,
      title: 'Complete project report',
      description: 'Write the final report for the current project.',
      dueDate: '2024-11-30',
      priority: 'High',
      completed: false,
    },
  ];
  
  export default sampleTasks;
  